using UnityEngine;
using System.Collections;
public class sideObjectScript : MonoBehaviour {
public RoadObjectScript OODQDDOOQC;
public int soIndex;
public string soName;
public int soAlign = 0;
public float soUVx = 0.1f;
public float soUVy = 1f;
public float m_distance = 10f;
public int objectType = 0;
public int position = 0;
public Material mat;
public bool weld = true;
public bool combine = true;
public bool ODOQQCODQO = true;
public string m_go = "";
public string OOOQCODOCO = "";
public string OOOCOCOCDD = "";
public GameObject goStart;
public GameObject goEnd;
public GameObject goInstantiated;
public int selectedRotation = 0;
static public string[] rotationOptions;
static public string[] uvStrings;
public int uvInt = 0;
public bool randomObjects = false;
public int childOrder = 0;
public string[] childOrderStrings;
public float density = 1f;
public float sidewaysOffset = 0f;
public int terrainTree = 0;
public string[] rotationStrings;
public int selectedYRotation = 0;
public int childCount = 0;
public float xPosition = 0f;
public float yPosition = 0f;
public float uvYRound = 0f;
public bool m_collider = false;
}
